export const products = [
  {
    id: 1,
    name: "Wheat Atta",
    type: "MP Lokwan",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./WheatFlour1.svg",
      "./WheatFlour2.svg",
      "./Chapati1.svg",
      "./WheatFlour3.svg",
      "./WheatFlour4.svg",
    ],
    rating: 5,
  },
  {
    id: 2,
    name: "Wheat Atta",
    type: "Sehori Sharbati",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./WheatFlour5.svg",
      "./WheatFlour6.svg",
      "./Chapati1.svg",
      "./WheatFlour7.svg",
      "./WheatFlour8.svg",
    ],
    rating: 5,
  },
  {
    id: 3,
    name: "Wheat Atta",
    type: "Sehori Sharbati Premium",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./WheatFlour9.svg",
      "./WheatFlour10.svg",
      "./Chapati1.svg",
      "./WheatFlour11.svg",
      "./WheatFlour12.svg",
    ],
    rating: 5,
  },
  {
    id: 4,
    name: "Jowar Atta",
    type: "White",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./JowarFlour1.svg",
      "./JowarFlour2.svg",
      "./JowarFlour3.svg",
      "./Bhakari1.svg",
      "./JowarFlour4.svg",
      "./JowarFlour5.svg",
    ],
    rating: 5,
  },
  {
    id: 5,
    name: "Jowar Atta",
    type: "White Premium",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./JowarFlour6.svg",
      "./JowarFlour7.svg",
      "./JowarFlour8.svg",
      "./Bhakari1.svg",
      "./JowarFlour9.svg",
      "./JowarFlour10.svg",
      "./JowarFlour11.svg",
    ],
    rating: 5,
  },
];
