export const products = [
  {
    id: 1,
    name: "Wheat Atta",
    type: "MP Lokwan",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./WheatFlour1.jpg",
      "./WheatFlour2.jpg",
      "./Chapati1.jpg",
      "./WheatFlour3.jpg",
      "./WheatFlour4.jpg",
    ],
    rating: 5,
  },
  {
    id: 2,
    name: "Wheat Atta",
    type: "Sehori Sharbati",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./WheatFlour5.jpg",
      "./WheatFlour6.jpg",
      "./Chapati1.jpg",
      "./WheatFlour7.jpg",
      "./WheatFlour8.jpg",
    ],
    rating: 5,
  },
  {
    id: 3,
    name: "Wheat Atta",
    type: "Sehori Sharbati Premium",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./WheatFlour9.jpg",
      "./WheatFlour10.jpg",
      "./Chapati2.jpg",
      "./WheatFlour11.jpg",
      "./WheatFlour12.jpg",
    ],
    rating: 5,
  },
  {
    id: 4,
    name: "Jowar Atta",
    type: "White",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./JowarFlour1.jpg",
      "./JowarFlour2.jpg",
      "./JowarFlour3.jpg",
      "./Bhakari1.jpg",
      "./JowarFlour4.jpg",
      "./JowarFlour5.jpg",
    ],
    rating: 5,
  },
  {
    id: 5,
    name: "Jowar Atta",
    type: "White Premium",
    desc: "Truly fresh milled whole grain atta - sourced from the farms of Sehore in Madhya Pradesh",
    images: [
      "./JowarFlour6.jpg",
      "./JowarFlour7.jpg",
      "./JowarFlour8.jpg",
      "./Bhakari1.jpg",
      "./JowarFlour9.jpg",
      "./JowarFlour10.jpg",
      "./JowarFlour11.jpg",
    ],
    rating: 5,
  },
];
