import { Inter } from "next/font/google";
import { announcements } from "@constants/AnnouncementBar";
import AnnouncementBar from "@components/AnnouncementBar";
import "./globals.css";
import Header from "@components/Header";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        <AnnouncementBar announcements={announcements} />
        <Header />
        {children}
      </body>
    </html>
  );
}
